openapi: 3.0.0
info:
  version: '0.1'
  title: Hello World
  description: Introducing open api 3.0.0

paths:
  /hello:
    get:
      tags:
        - hello
      operationId: src.hello.hello_world
      description: Returns hello world string
      responses:
        '200':
          description: 'Success'
  /sum/<arg1>/<arg2>:
    get:
      tags:
        - sum
      operationId: src.sum.sum
      description: Returns the sum of two numbers
      responses:
        '200':
          description: 'Success'
  /description:
    get:
      tags:
        - description
      operationId: src.description.desc
      description: Returns what the model does
      responses:
        '200':
          description: 'success'
  /data:
    get:
      tags:
        - data
      operationId: src.data.data
      description: place where data for model goes in
      responses:
        '200':
          description: 'success'
  /question:
    get:
      tags:
        - question
      operationId: src.question.question
      description: Ask questions about service here via the webpage
      responses:
        '200':
          description: 'success'
  /predict/{id}:
    get:
      tags:
        - pred
      operationId: src.model.model
      description: Returns the prediction for a given set of inputs
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
        - in: query
          name: metadata
          schema:
            type: boolean
      responses:
        '200':
          description: 'Success'
servers:
        - url: 'http://localhost:8000/e222'
